using Markdown, Test, BenchmarkTools, StatsBase, BioSequences
md"""
Given: A protein string of length at most 1000 aa.
Return: The total number of different RNA strings from which the protein could have been translated, modulo 1,000,000. (Don't neglect the importance of the stop codon in protein translation.)
"""
standard_trans = ncbi_trans_table[1] |> values |> countmap
function infer_mRNA(x)
    n = 1000000
    counter = standard_trans[AA_Term]
    for aa in LongAA(x)
        counter = mod(counter * standard_trans[aa], n)
    end
    counter
end
@test infer_mRNA("MA") == 12

x = "MFAWIKAEKVRQFHVAPCCLRLEGLYNFIVHSGKKPSNEIRCQCSTWENNSQKWPCPCFICLMPFQMKVRQQGYEQWQIETQTMYITSGSNVDCLQIANSWIHARTMHDVQDGYCVQERKKKQNRSDHLQWDCMRKHIWICWSENDIHFHHNAIGGVGFQGTDSIIEMHSMRYIADYLHDYLDCTKRIQDFPNYFRWKSQIEQAFNWYDMTRENMVHVRCFWSFTDSGEQMDYATPSFRVKCTEFEKNDLNSAEIWKFYTLGPSVYRCTHSNSQRNKGSVWWFIFRGKTMSMYECMCKIVRAGKVFHEYFYKEWNPFMIHCQGRQHCFWWMQVCDEIKCGCNAHLKFEVRQYLSKQKGLRCQREFKTPNWCCSWQYWIPTWSKQRDKIYCGFHMNMDWNLCPALRIVLTCPVHHDCFRVCDVSSCQMQGNAYDGGCNHPWQGGPSAQRDNKMFLWLISAKPDNWGHYHPGFMCKTPNTHVASCKCGMAMQTETATDSSLHVSFQGHLLKDQMHRKHGVTAKHLHAGFYTMMLVPQMEATRMQNQGWRYMGLGPMSNRIAWRACVAEGKAKPWYFNLGWCSKFLIKNETANTQWQFNNQACYDFPMLCPNWVGPYVEKGQIAYMWQPMMIHYRVIAIGMIRSICVFYVARAAKSDCREESGFEDIIDVWDAMNYKDTLRFRRMENTRDQLQTWMEINFVSPTSELNEYAWSKCNNCAQANDSRMEAAGEDECVPDSSNPRAECWYVFPASCFQQNPLWEQPYRCNLEEMQMKLELSPPIGYGVRQFQPMNAIMYENAYAHNDPNKHAKQTQHDLAIQNAYCSPMIQAHDDWQCCRFDYRWHAGTLANSIPQGKGGMIDQCLGFFDAARWETNSFELNKHWFQIPHPPMSITYESLTQVIENCMYRTRMVELGLWWQKQRILLLRFCYMRRVEGIWEILAVHGAPAPLWETAVHVFVWLWMHKPMSGIVAALECQHFRHHQAHWMTPQRATNCWSAWAKY"
@benchmark infer_mRNA(x)

md"""
Real answer using BigInt
"""
begin
    n = 1000000
    counter = BigInt(standard_trans[AA_Term])
    for aa in LongAA(x)
        counter = counter * standard_trans[aa]
    end
    counter
end